name: Build APK

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip python3-pip git
        pip install --upgrade cython buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: varia-app-debug-apk
        path: bin/*.apk
